# These are supported funding model platforms

github: #HemantTheCoder #Vivektheprogrammar
patreon: ['https://www.patreon.com/hyperlapseinc']
paypal: ['https://paypal.me/alshelp']
issuehunt: ['https://issuehunt.io/u/hemantthecoder']
